### ISSUE TITLE
com.android.dex.DexException

### ISSUE THREAD

**Issue by upandrun** [katzer/cordova-plugin-local-notifications#1020]
I am using a Meteor.js with my projects. So I added `cordova-plugin-local-notifications` and after I running `meteor run android-device` I am getting this error:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)
```

Also for some reason Meteor downloads `com.phonegap.plugins.PushPlugin`. Maybe they conflict some how.

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old.

**Comment by rwillett** [comment]
No update from original poster so closing.
