### ISSUE TITLE
I am not able to install the following error coming

### ISSUE THREAD

**Issue by pareta2** [katzer/cordova-plugin-local-notifications#1157]
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
    at checkID (/usr/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /usr/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/usr/lib/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/plugman/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/plugman/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/plugman/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)

**Comment by rwillett** [comment]
Is this resolved now?

**Comment by rwillett** [comment]
Closed as no response from original poster.
