### ISSUE TITLE
Local notification cause the app in android Nougat to force close.

### ISSUE THREAD

**Issue by LtotheWT** [katzer/cordova-plugin-local-notifications#1360]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Local notification not working in android nougat.

## Your Environment

* Plugin version : 0.8.5
* Platform: android 
* OS version: Windows 10
* Device manufacturer / model: Samsung S8
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config
* Ionic Version (if using Ionic) 3.7.0

## Expected Behavior

notification should work and wont make the app to crash.

## Actual Behavior

Local notification makes app in android nougat to crash.

## Steps to Reproduce
when notification is triggered the app will crash.

## Context

normal notification. 

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by LtotheWT** [comment]
hi guys any idea ?

**Comment by floriansimon1** [comment]
Hi! Same problem here. Got the following trace from Android studio:

```
08-22 15:18:00.522 21218-21218/lu.vendor.application E/AndroidRuntime: FATAL EXCEPTION: main
Process: lu.vendor.application, PID: 21218
java.lang.RuntimeException: Unable to start receiver de.appplant.cordova.plugin.localnotification.TriggerReceiver: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/lu.vendor.application/cache/localnotification/sound.mp3 exposed beyond app through Notification.sound
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3369)
    at android.app.ActivityThread.-wrap20(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6776)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
 Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/lu.vendor.application/cache/localnotification/sound.mp3 exposed beyond app through Notification.sound
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
    at android.net.Uri.checkFileUriExposed(Uri.java:2346)
    at android.app.NotificationManager.notifyAsUser(NotificationManager.java:323)
    at android.app.NotificationManager.notify(NotificationManager.java:292)
    at android.app.NotificationManager.notify(NotificationManager.java:276)
    at de.appplant.cordova.plugin.notification.Notification.showNotification(Notification.java:239)
    at de.appplant.cordova.plugin.notification.Notification.show(Notification.java:224)
    at de.appplant.cordova.plugin.notification.TriggerReceiver.onTrigger(TriggerReceiver.java:45)
    at de.appplant.cordova.plugin.localnotification.TriggerReceiver.onTrigger(TriggerReceiver.java:48)
    at de.appplant.cordova.plugin.notification.AbstractTriggerReceiver.onReceive(AbstractTriggerReceiver.java:75)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3362)
    at android.app.ActivityThread.-wrap20(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6776) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by jsuryahyd** [comment]
Same problem. actually, I get warnings in the console about unknown variables(firstAt,message) while debugging in chrome. When I run the function from console, I get system notification "App keeps closing", and the app is closed. Is this specific for Nougat?

**Comment by jsuryahyd** [comment]
Update. It is working now for me - mostly. But still do not have full control. Cancelling a notification(swiping left on notification) seems to cancel the schedule. Guess we have to go through the code extensively.

**Comment by Thamodharank** [comment]
Hello Team,

I am facing the same problem. The workaround didn't work for me. Is there any solution for this?

Thanks in Advance.

**Comment by shamank** [comment]
I'm receiving:
```
[16:12:42]  console.warn: Unknown property: firstAt 
[16:12:42]  console.warn: Unknown property: priority 
```
While running on device. Should I take care of this? In docs they are still named like that, but I'm getting some randome exceptions like:
```
Error: Uncaught (in promise): TypeError: options.at.getTime is not a function
TypeError: options.at.getTime is not a function
```
I think it's related to it.

Is it ok using "at" instead of "firstAt"? I'm using "every" (week).

**Comment by katzer** [comment]
The `android.os.FileUriExposedException` has been fixed already - thanks.
