### ISSUE TITLE
Ionic package for iOS - Failed to install de.appplant.cordova.plugin.local-notification

### ISSUE THREAD

**Issue by EvPut** [katzer/cordova-plugin-local-notifications#1405]
**Plugin version:** 0.8.5
**Platform:** Ionic package for iOS 

**ionic/cli-utils:** 1.15.2
**ionic (Ionic CLI) :** 3.15.2
**cordova (Cordova CLI) :** 7.0.1
**ionic/app-scripts :** 2.1.3
**Cordova Platforms  :** android 6.2.3 ios 4.4.0
**Ionic Framework    :** ionic-angular 3.6.0
**Node              :** v7.10.0
**npm               :** 4.5.0

**cordova plugins**
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-battery-status 1.2.4 "Battery"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Log:**
```
Using cordova-fetch for cordova-ios@4.4.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.evput.child
	Name: Родные всегда рядом
iOS project created with cordova-ios@4.4.0
Discovered plugin "cordova-plugin-battery-status" in config.xml. Adding it to the project
Installing "cordova-plugin-battery-status" for ios
Adding cordova-plugin-battery-status to package.json
Saved plugin info for "cordova-plugin-battery-status" to config.xml
Discovered plugin "cordova-plugin-console" in config.xml. Adding it to the project
Installing "cordova-plugin-console" for ios
Adding cordova-plugin-console to package.json
Saved plugin info for "cordova-plugin-console" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-geolocation" in config.xml. Adding it to the project
Installing "cordova-plugin-geolocation" for ios
Installing "cordova-plugin-compat" for ios
Adding cordova-plugin-geolocation to package.json
Saved plugin info for "cordova-plugin-geolocation" to config.xml
Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it to the project
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

             In order to run this plugin, you need to obtain Google Maps API key for iOS.
             Visit https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation

             Check our release notes.
             https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Release-Notes
        
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
Discovered plugin "cordova-plugin-mauron85-background-geolocation" in config.xml. Adding it to the project
Installing "cordova-plugin-mauron85-background-geolocation" for ios
Adding cordova-plugin-mauron85-background-geolocation to package.json
Saved plugin info for "cordova-plugin-mauron85-background-geolocation" to config.xml
Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project
Installing "cordova-plugin-network-information" for ios
Adding cordova-plugin-network-information to package.json
Saved plugin info for "cordova-plugin-network-information" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
Installing "cordova-plugin-x-socialsharing" for ios
Installing "es6-promise-plugin" for ios
Adding cordova-plugin-x-socialsharing to package.json
Saved plugin info for "cordova-plugin-x-socialsharing" to config.xml
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Installing "ionic-plugin-keyboard" for ios
Adding ionic-plugin-keyboard to package.json
Saved plugin info for "ionic-plugin-keyboard" to config.xml
Discovered plugin "de.appplant.cordova.plugin.local-notification" in config.xml. Adding it to the project
Installing "de.appplant.cordova.plugin.local-notification" for ios
Plugin dependency "cordova-plugin-device@1.1.6" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on ios.
Failed to install 'de.appplant.cordova.plugin.local-notification': CordovaError: Failed to fetch plugin cordova-plugin-app-event via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm ERR! addLocal Could not install /Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-plugin-app-event" "--production" "--save"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path /Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/package/workspace/apps-4ef0627a-66/cordova/npm-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:215:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Failed to restore plugin "de.appplant.cordova.plugin.local-notification" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-app-event via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm ERR! addLocal Could not install /Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-plugin-app-event" "--production" "--save"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path /Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/package/workspace/apps-4ef0627a-66/cordova/node_modules/cordova-plugin-app-event'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/package/workspace/apps-4ef0627a-66/cordova/npm-debug.log
--save flag or autosave detected
Saving ios@~4.4.0 into config.xml file ...
```

**Comment by stevesum** [comment]
https://cordova.apache.org/news/2017/05/04/cordova-7.html

use --nofetch attribute or config see the link

2017-10-27 15:11 GMT+02:00 EvPut <notifications@github.com>:

**Comment by katzer** [comment]
`Cordova plugin add --nofetch ...`

**Comment by EvPut** [comment]
For ionic cloud package build also?
don't build ((
