### ISSUE TITLE
The supported android API's in 0.9.0_beta.1

### ISSUE THREAD

**Issue by jota0222** [katzer/cordova-plugin-local-notifications#1490]
Hello everyone,

I want to know if the last relese is going to support android API's lower than 23 (Android 6 Marshmallow). I am trying to make it work on API level 18 (Android 4.3 JellyBean) at least but the compiler throws me exceptions related with the minimum SDK version in functions called by the plugin. 

## Your Environment

* Plugin version: 0.9.0_beta.1
* Platform: Android
* OS version: 4.3 Jellybean
* Device manufacturer / model: Huawei Y530
* Cordova version: 7.1.0
* Cordova platform version: android 6.3.0
* Plugin config: default
* Ionic Version: 3.19.0 (i'm using phonegap 7.1.1 too in another project)

## Expected Behavior

Everithing working on android API levels lower than 23

## Actual Behavior

Everything working on API levels grater than 23 and partial compatibility in API level 21

## Steps to Reproduce

  1. Create a Cordova project and add some code for notifications
  2. Set the minimum SDK lower than 21 in the config file
  3. Add android platform
  4. Build
  5. Test apk on a smartphone with an Android OS lower than 5

## Context
I've looking in the plugins code and I've found that the NotificationManager are not fully available for API lower than 23.

## Debug logs
```
01-03 09:58:46.625 10024-10024/? I/SELinux: Function: selinux_android_load_priority [0], There is no sepolicy file.
                                             
01-03 09:58:46.625 10024-10024/? I/SELinux: Function: selinux_android_load_priority , priority version is VE=SEPF_GT-I9195L_4.4.2_0065
                                             
                                             
01-03 09:58:46.635 10024-10024/? I/SELinux: selinux_android_seapp_context_reload: seapp_contexts file is loaded from /seapp_contexts
01-03 09:58:46.635 10024-10024/? E/dalvikvm: >>>>> Normal User
01-03 09:58:46.635 10024-10024/? E/dalvikvm: >>>>> com.kesslab.standlan [ userId:0 | appId:10193 ]
01-03 09:58:46.635 10024-10024/? D/dalvikvm: Late-enabling CheckJNI
01-03 09:58:46.776 10024-10024/com.kesslab.standlan D/AndroidRuntime: Shutting down VM
01-03 09:58:46.776 10024-10024/com.kesslab.standlan W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41996da0)
01-03 09:58:46.776 10024-10024/com.kesslab.standlan E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.kesslab.standlan, PID: 10024
                                                                      java.lang.RuntimeException: Unable to get provider de.appplant.cordova.plugin.notification.util.AssetProvider: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.notification.util.AssetProvider" on path: DexPathList[[zip file "/data/app/com.kesslab.standlan-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.kesslab.standlan-1, /vendor/lib, /system/lib]]
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4827)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:174)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:146)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.notification.util.AssetProvider" on path: DexPathList[[zip file "/data/app/com.kesslab.standlan-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.kesslab.standlan-1, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4827) 
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710) 
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:174) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:146) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5593) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
```

![imagen](https://user-images.githubusercontent.com/12126375/34525273-58c4f9a2-f06c-11e7-886f-b9bcd7ffe44f.png)

**Comment by katzer** [comment]
_0.9.0_beta.1_ supports Android 6+

_master_ supports Android 4.4+.

Android 8 is partly supported as of now.

**Comment by katzer** [comment]
Hope that answers your question.
