### ISSUE TITLE
Hundreds of crash reports from Google Play Console after deploying 0.9.0-beta3

### ISSUE THREAD

**Issue by alesgenova** [katzer/cordova-plugin-local-notifications#1541]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta3
* Platform: Android
* OS version: 8.1 / 8.0
* Device manufacturer / model: Mostly Pixels
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): cordova-android 6.4.0
* Plugin config
* Ionic Version (if using Ionic) 3.9.2, using the plugin without ionic-native layer

## Actual Behavior

After deploying an update to the play store a few days ago, I have been getting hundreds of crash reports from Google for devices running Android 8.1. and 8.0 (error attached below). No user complained yet, so I don't know if the problem has any actual impact. I have tested the app on a Nexus 5X running android 8.1 as well as a few emulators, and I haven't noticed any issues.

I am reporting this here just so you are aware, in case there is some actual issue.

## Debug logs

This is the error google has been reporting

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3194)
  at android.app.ActivityThread.-wrap17 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1672)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:387)
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:372)
  at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:167)
  at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:167)
  at de.appplant.cordova.plugin.notification.Manager.getPrefs (Manager.java:399)
  at de.appplant.cordova.plugin.notification.Manager.getIds (Manager.java:206)
  at de.appplant.cordova.plugin.notification.Manager.getOptions (Manager.java:291)
  at de.appplant.cordova.plugin.notification.receiver.AbstractRestoreReceiver.onReceive (AbstractRestoreReceiver.java:64)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3187)
```

## Source code

This is a simplified version of the code I use to set notifications:

```typescript
  setNotification(every:string, firstAt:Date){

    let text = this.notificationStrings.daily;

    let n:number = 30; // arbitrary large number
    
    let notifications = [];

    for (let i:number=0; i<n; i++){
      let theAt: Date = new Date(firstAt);
      if (every == 'minute'){
        theAt.setMinutes(theAt.getMinutes()+i);
      }else if (every == 'hour'){
        theAt.setHours(theAt.getHours()+i);
      }else if (every == 'day'){
        theAt.setDate(theAt.getDate()+i);
      }else if (every == 'week'){
        theAt.setDate(theAt.getDate()+i*7);
      }
      notifications.push(
        {
          id: i,
          title: this.notificationStrings.title,
          text: text,
          icon: "",
          sound: true,
          priority: 1,
          smallIcon: "res://"+this.notificationStrings.icon,
          foreground: true,
          wakeup: false,
          trigger:{
            at: theAt
          }
        }
      );

    }

    cordova.plugins.notification.local.cancelAll(
      () => {
        cordova.plugins.notification.local.schedule(notifications,
          () => {
            console.log("notification set ", firstAt, every);
          }
        );
      }
    );
}
```

**Comment by alesgenova** [comment]
@katzer any idea about this?
the crash reports keep on coming, and they involve devices running Android 8.0 and 8.1

**Comment by katzer** [comment]
@alesgenova the plugin still does not support Android 8, just basic support because they introduced breaking changes and a fully new concept. That will come into the plugin as well with 0.9-rc.0 but might come along with breaking changes compared to 0.9-beta

**Comment by jayseb11** [comment]
I am observing the same exception from my latest deployment as well. Even though users have not reported any issues, I am worried that the notification prevents the user from accessing the app. 

Do you have any idea on when the plugin might be able to fully support Android 8?

**Comment by Reactor13** [comment]
In may 2018 we wait Android 9 release.
But still we don't have Android 8 support in this plugin (the latest plugin with this functionality for Cordova).

@katzer I understand, that this plugin is free. But it is important for us.
I can donate some money for you for support this plugin (pay for support in fact). Can we talk about it?

**Comment by Reactor13** [comment]
`04-17 00:39:31.251 879-902/? I/ActivityManager: Start proc 1830:ru.airbits.ihamster/u0a185 for broadcast ru.airbits.ihamster/de.appplant.cordova.plugin.localnotification.RestoreReceiver
04-17 00:39:31.349 1830-1830/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: ru.airbits.ihamster, PID: 1830
                                                 java.lang.RuntimeException: Unable to start receiver de.appplant.cordova.plugin.localnotification.RestoreReceiver: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                  Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
                                                     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:387)
                                                     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:372)
                                                     at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
                                                     at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
                                                     at de.appplant.cordova.plugin.notification.Manager.getPrefs(Manager.java:399)
                                                     at de.appplant.cordova.plugin.notification.Manager.getIds(Manager.java:206)
                                                     at de.appplant.cordova.plugin.notification.Manager.getOptions(Manager.java:291)
                                                     at de.appplant.cordova.plugin.notification.receiver.AbstractRestoreReceiver.onReceive(AbstractRestoreReceiver.java:64)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

**Comment by jpierront** [comment]
@Reactor13 Do you still use your fix without any side effect? Or have you found another solution?

**Comment by Reactor13** [comment]
@jpierront Yes,  i still use my fix without any side effect and waiting for plugin update...

**Comment by Reactor13** [comment]
@jpierront as i see - you have forgot this in your commit:
import android.os.UserManager;

**Comment by jpierront** [comment]
Thanks for your help :) I'll try it soon !

**Comment by jpierront** [comment]
Great, notifications are triggered even after device reboot ! (Tested on Android 4.4, 5.1, 6.0, 7.1, 8.1).
Thx @Reactor13 :D

**Comment by TianleZhang** [comment]
When can this ticket got released?

**Comment by marcovtwout** [comment]
@Reactor13 Could you explain how your proposed change properly fixes the issue? If I understand correctly, the onReceive() handler is used to restore notifications on reboot. Your addition will prevent a crash when Manager.getInstance() is called, but by returning early it will also skip the code that restores notifications on reboot. Or isn't that piece needed on API >= 24?

**Comment by h3nr1ke** [comment]
Just to complement, repeated notifications are not working os Android 8 with the @Reactor13 fix, still working on Android 5.

**Comment by husainsr** [comment]
After reboot notification is not come.
Android: 7.1.2
Mobile: MI 5A.

**Comment by husainsr** [comment]
Any update on notification after reboot ?

**Comment by luisomoreau** [comment]
Hello, 
Is there any "official" release that fixes this issue?
Thank you,
Louis

**Comment by husainsr** [comment]
i had install cordova plugin add `cordova-plugin-local-notification@0.9.0-beta.3` and check with the same,
set notification then reboot my device but notification not come at scheduled time.
I don't know how to resolve this.

**Comment by GitToTheHub** [comment]
@husainsr 
You must use the master version of this plugin to fix the issue.

**Comment by HansKrywaa** [comment]
Can someone please build a new release Version? I generally don't like to install from Git Branches directly. @dpa99c

**Comment by julianlecalvez** [comment]
> @husainsr
> You must use the master version of this plugin to fix the issue.

I have the same crash logs, and I'm using the beta-3. 
What is the difference in term of features between the master and the beta 3 ? (I don't want to switch if there's a difference)

**Comment by jrista** [comment]
We just released an updated version of an app that uses 0.9.0-beta.3, and we have started receiving significant numbers of the same exceptions. It does not sound like the previously proposed fix is complete, as after reboot notifications are no longer received. 

I'm not an Android native programmer, I usually use Ionic, so I'm not well versed in the native APIs here. Does anyone know how to fix this issue, and still ensure that previously scheduled local notifications will work after reboot?

**Comment by rahmadid** [comment]
hi all, perhaps you can try this fork, it is more recent and still maintained:
https://github.com/timkellypa/cordova-plugin-local-notifications

hope it helps. thanks.

**Comment by jrista** [comment]
@rahmadid Thank you for the recommendation. I'll take a look.

**Comment by aleygues** [comment]
Hi @rahmadid I tried this fork but I'm getting buil errors such as:

`/.../platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:498: error: package NotificationCompat does not exist
        NotificationCompat.Builder builder = Notification.getCachedBuilder(key);`

And 99 other errors of that type. Did I miss something?

**Comment by rahmadid** [comment]
@aleygues Maybe because that plugin uses androidx. If you haven't migrated to androidx yet, you can try these two plugins for easy migration:
https://github.com/dpa99c/cordova-plugin-androidx
https://github.com/dpa99c/cordova-plugin-androidx-adapter

Thanks.

**Comment by aleygues** [comment]
Hi @rahmadid thanks! I'll give it a try

**Comment by aleygues** [comment]
Hi @rahmadid I just tried by bumping my cordova app from Cordova Android 8 to 9. By enabling AndroidX, this plugin build successfully, unfortunetly, some other plugins (including Phonegap Push, Camera and File Opener) seems to by incompatible with AndroidX. 

I'm still stuck, but not for the same reason ^.^. Thanks for the help!

**Comment by Carlosps** [comment]
As @rahmadid mentioned, I would suggest to migrate to https://github.com/timkellypa/cordova-plugin-local-notifications. I have tested with [that ](https://github.com/timkellypa/cordova-plugin-local-notifications) version of the plugin and the crashes have dropped considerably.
