### ISSUE TITLE
Application crashes when scheduling a notification (using Cocoon)

### ISSUE THREAD

**Issue by Jack37** [katzer/cordova-plugin-local-notifications#1632]
I am developing HTML5 games using Phaser JS framework, and Cocoon JS to pack the game into Android APK file. I need to use notifications in my games, but when I schedule new notification, the game crashes. Same issue as #833.

## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: 4.2.2, 7.1.2 (and more)
* Device manufacturer / model: Samsung GT-I9060, Samsung GT-I9195, Emulator (and more)
* Cordova version: 6.2.3
* Cordova platform version: 6.2.3
* Plugin config: -
* Ionic Version (if using Ionic): -

## Expected Behavior

Notification should be scheduled and received.

## Actual Behavior

Application crashes on notification schedule.

## Steps to Reproduce

Phaser JS and Cordova need to be included.

  1. Create empty Phaser JS application.
  2. Add code to schedule notification.
  3. Compile application to APK using cocoon.io cloud compiler.
  4. Install APK on mobile phone and run.

## Context
`
cordova.plugins.notification.local.schedule({
    title: 'My first notification',
    text: 'Thats pretty easy...',
    foreground: true
});
`

## Debug logs
`
FATAL EXCEPTION: pool-1-thread-3
java.lang.NumberFormatException: Invalid int: "null"
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:375)
at java.lang.Integer.parseInt(Integer.java:366)
at de.appplant.cordova.plugin.notification.Options.getColor(Options.java:265)
at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:130)
at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:94)
at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:80)
at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:217)
at de.appplant.cordova.plugin.localnotification.LocalNotification.access$000(LocalNotification.java:50)
at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
`

**Comment by Jack37** [comment]
It seems that https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/src/android/notification/Options.java#L317
returns "null" instead of null, and that is causing error in 
https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/src/android/notification/Options.java#L331
because the null check is skipped
https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/src/android/notification/Options.java#L319

Same for
https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/src/android/notification/Options.java#L251

I fixed it by explicitly setting `led: '0', color: '0'` in my notification. Application doesn't crash anymore, but notifications still don't arrive. I will keep trying.

**Comment by Jack37** [comment]
I think there's a bug in Cocoon compiler. If I choose Canvas+, it doesn't work, but if I choose Webview, the plugin works fine. Closing this, as you probably can't fix this.
