### ISSUE TITLE
Cannot interact with Local Notification Queue

### ISSUE THREAD

**Issue by CharlieIGG** [katzer/cordova-plugin-local-notifications#1673]
On Ionic Framework 3:
1. `getAll()` returns empty array
2. `clearAll()` and `cancelAll()` don't seem to work, since scheduled notifications are still firing after that.

## Your Environment

* Plugin version:  cordova-plugin-local-notification@0.9.0-beta.3 + @ionic-native/local-notifications@4.12.2
* Platform: Android and iOS
* OS version: Android 8 & iOS 11
* Device manufacturer / model: Motorola Z2 Play & iPhone X
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
```
Installed platforms:
  android 6.3.0
  ios 4.5.5
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config: Default
* Ionic Version (if using Ionic): 3

## Expected Behavior

1.  If I schedule a notification and call `getAll()` or `getAllIds()` I should see the just-scheduled notification.

2. If I call `cancelAll()` and `clearAll()` no previously-scheduled local notification should fire.

## Actual Behavior

1.  If I schedule a notification and call `getAll()` or `getAllIds()` I get an empty array after the promise resolves.

2. If I call `cancelAll()` and `clearAll()` previously-scheduled local notifications are firing anyways.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

```typescript
import { LocalNotifications } from '@ionic-native/local-notifications';

@Injectable()
export class LocalNotificationProvider {
  constructor(
    private localNotifications: LocalNotifications,
  ){
    this.localNotifications.schedule({
      id: 1,
      title: "Title!",
      text: "Some Text",
      trigger: { at: new Date(new Date().getTime() + 5000) },
      led: 'FF0000',
      sound: null,
      vibrate: true,
    });
    this.localNotifications.getAll().then(notifs => console.log(notifs)) // <----- Returns []
    this.localNotifications.cancelAll() // <----- Does nothing, the above notification still fires at ~5s
  }
}
```
## Context

I need to be able to schedule notifications and then cancel them IF a certain event happens in the app.

## Debug logs
These are the logs for when something similar to the above snippet is called TWICE, including the **immediate** attempt to `getAll`  and `cancelAll`:

```
(...)
09-05 17:21:59.079   617   881 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
09-05 17:22:00.607  2307  2307 I ADSPD   : Watchdog 2 new value: 007030e7 Last Exp Value: ffffffff
09-05 17:22:00.610  2307  2307 I ADSPD   : Watchdog 3 new value: 007030da Last Exp Value: ffffffff
09-05 17:22:02.133   617   881 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
09-05 17:22:02.439 13949  6234 E ActivityThread: Failed to find provider info for com.teslacoilsw.notifier
09-05 17:22:02.444 13949 13949 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.notification.local.fireEvent("cancelall",{"event":"cancelall","foreground":true,"queued":false}))
09-05 17:22:02.451 13949 13949 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.notification.local.fireEvent("cancelall",{"event":"cancelall","foreground":true,"queued":false}))
09-05 17:22:02.469 13949  6234 D local-notification: Next trigger at: Wed Sep 05 18:00:00 CDT 2018
09-05 17:22:02.476 13949 13949 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.notification.local.fireEvent("add",{"id":2,"title":"Appointment Reminder","text":"You are now entering your appointment timeframe. The Technician will let you know when he is on the way.","trigger":{"at":1536188400743,"type":"calendar"},"led":"FF0000","vibrate":true,"actions":[],"attachments":[],"autoClear":true,"clock":true,"defaults":0,"groupSummary":false,"launch":true,"lockscreen":true,"number":0,"priority":0,"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},"silent":false,"smallIcon":"res:\/\/icon","timeoutAfter":false,"wakeup":true,"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.3"}},{"event":"add","foreground":true,"queued":false,"notification":2}))
09-05 17:22:02.485 13949 13949 D SystemWebChromeClient: http://192.168.1.57:8100/build/main.js: Line 1280 : 
09-05 17:22:02.485 13949 13949 I chromium: [INFO:CONSOLE(1280)] "", source: http://192.168.1.57:8100/build/main.js (1280)
09-05 17:22:02.486 13949  6234 D local-notification: Next trigger at: Wed Sep 05 17:24:02 CDT 2018
09-05 17:22:02.495 13949 13949 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.notification.local.fireEvent("add",{"id":1,"title":"Appointment Confirmation","text":"We have an appointment scheduled at  7:00 PM Do you still want us to arrive?","trigger":{"at":1536186242430,"type":"calendar"},"led":"FF0000","vibrate":true,"actions":[],"attachments":[],"autoClear":true,"clock":true,"defaults":0,"groupSummary":false,"launch":true,"lockscreen":true,"number":0,"priority":0,"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},"silent":false,"smallIcon":"res:\/\/icon","timeoutAfter":false,"wakeup":true,"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.3"}},{"event":"add","foreground":true,"queued":false,"notification":1}))
09-05 17:22:02.505 13949 13949 D SystemWebChromeClient: http://192.168.1.57:8100/build/main.js: Line 1280 : 
09-05 17:22:02.505 13949 13949 I chromium: [INFO:CONSOLE(1280)] "", source: http://192.168.1.57:8100/build/main.js (1280)
09-05 17:22:11.059  8840   942 D HeadsetStateMachine: Disconnected process message: 10, size: 0
09-05 17:22:11.060  8840   942 D HeadsetStateMachine: Enter processIntentBatteryChanged()
09-05 17:22:11.060  8840   942 D HeadsetStateMachine: Exit processIntentBatteryChanged()
09-05 17:22:11.060  8840   942 D HeadsetStateMachine: Exit Disconnected processMessage() 
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: Error while reading from SharedPreferences 
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2407)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:386)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:373)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:12)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at com.google.android.gms.tagmanager.zza$1.zzXg(Unknown Source:7)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at com.google.android.gms.tagmanager.zza.zzXf(Unknown Source:9)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at com.google.android.gms.tagmanager.zza.zzb(Unknown Source:0)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at com.google.android.gms.tagmanager.zza$2.run(Unknown Source:2)
09-05 17:22:12.496  1644  1844 W AdvertisingIdClient: 	at java.lang.Thread.run(Thread.java:764)
09-05 17:22:18.332  2824  2840 I zygote  : Background concurrent copying GC freed 297300(13MB) AllocSpace objects, 243(5MB) LOS objects, 42% free, 24MB/43MB, paused 844us total 218.086ms
09-05 17:22:25.276  2824  3353 D BatteryService: uevent={POWER_SUPPLY_VOLTAGE_NOW=4385808, POWER_SUPPLY_CHARGE_RATE=Normal, POWER_SUPPLY_HEALTH=Good, POWER_SUPPLY_CURRENT_NOW=-292509, POWER_SUPPLY_PRESENT=1, SUBSYSTEM=power_supply, POWER_SUPPLY_TEMP=302, SEQNUM=153836, ACTION=change, POWER_SUPPLY_NAME=battery, POWER_SUPPLY_STATUS=Charging, POWER_SUPPLY_CHARGE_COUNTER=2967441, POWER_SUPPLY_CAPACITY=97, DEVPATH=/devices/soc/qpnp-smbcharger-17/power_supply/battery}
(...)
``` 

It is apparent from the above snippet that the Get and Cancel methods may be being called AFTER the schedule is complete (why does `schedule` not return a promise BTW?), but even if I call them much later, the same behavior persists.

**Comment by Tawpie** [comment]
Agreed, it would be nicer if `schedule` returned a promise. But you can listen for the add event and do your `getAll` in that handler. It's been my experience that the OS can take its sweet time doing the scheduling (seconds) and that the plugin can step on itself if things are happening too quickly.

```
// ******* removable listener for on-scheduled

/**
 * adds the Katzer 'add' listener which fires when Katzer has actually
 * scheduled the notification. Has to be done with a function in the
 * callback or we won't be able to remove it
 */
export function attachOnScheduledNotificationListener() {
  if (isLocalNotificationPluginValid()) {
    cordova.plugins.notification.local.on("add", handleOnLocalNotificationScheduled);
    console.log("Katzer onScheduled (add) listener created");
  }
}

export function removeOnScheduledNotificationListener() {
  if (isLocalNotificationPluginValid()) {
    cordova.plugins.notification.local.un("add", handleOnLocalNotificationScheduled);
    console.log("Katzer onScheduled (add) listener removed");
  }
}
```

**Comment by CharlieIGG** [comment]
Thanks @Tawpie you're actually right and getAll does actually work 🤔 

Your response gave me the idea to wrap the `cancelAll()` inside `getAll()`'s callback and now that works too, like this: 

```
private resetLocalNotifications(): void {
        this.localNotifications.getAll().then(reminders => {
            this.localNotifications.cancelAll();
            this.localNotifications.clearAll();
        })
    }
```
