### ISSUE TITLE
Ionic/Angular Resources$NotFoundException: Drawable android:id/icon

### ISSUE THREAD

**Issue by minicatsCB** [katzer/cordova-plugin-local-notifications#1820]
## Your Environment

* Plugin version: 0.8.4
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: SM-J530F/DS
* Cordova version (```cordova -v```): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```): android 8.0.0
* Plugin config
* Ionic Version (if using Ionic): 4.12.0

## Expected Behavior

1. Open the app.
2. Wait for five seconds.
3. A local notification should appear in the status bar.

## Actual Behavior

1. Open the app.
2. The app crashes.

## Steps to Reproduce

1. Create a simple Ionic app: `ionic start notif sidemenu --type=ionic-angular`.
2. Install Cordova: `npm install -g ionic cordova`.
3. Install the Inonic Native wrapper for the plugin following the Ionic [documentation](https://ionicframework.com/docs/v3/native/local-notifications/): `npm install --save @ionic-native/local-notifications@4`.
4. Install the plugin itself: `ionic cordova plugin add cordova-plugin-local-notification@0.8.4`. If I follow the official Ionic documentation, it installs the beta version 0.9.0-beta-2, but I don't want to use the beta in production, so I choose 0.8.4. (Anyway, with both versions the results are the same).
5. Add this plugin to your app's module in `src/app/app.module.ts`.
```
...
import { LocalNotifications } from '@ionic-native/local-notifications';
...

...
 providers: [
    StatusBar,
    SplashScreen,
    LocalNotifications,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
...
```
6. Schedule a notification after five seconds after entering the view in `src/pages/home/home.ts`:
```javascript
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { LocalNotifications } from '@ionic-native/local-notifications';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  public isNotificationScheduled = false;

  constructor(public navCtrl: NavController,
              private localNotifications: LocalNotifications) {

  }

  public ionViewDidEnter() {
    this.localNotifications.schedule({
      text: 'Delayed ILocalNotification',
      trigger: {at: new Date(new Date().getTime() + 3600)},
      led: 'FF0000',
      sound: null
    });

    console.log("Notification is scheduled");
    this.isNotificationScheduled = true;
  }

}
```
7. (Optional) Add a visual indicator to `src/pages/home/home.html`. I did this to have something that tells me if the notification has been scheduled.
```html
<p [ngStyle]="{'background-color': isNotificationScheduled ? 'green' : 'red' }">Notification is scheduled</p>
```

## Context
I'm trying to use this plugin in a bigger project but I can't get it to work. I decided to create a simple Ionic app with minimal code to try to isolate the problem.

## Debug logs
  * No logs in the DevTools. However, if I run `adb logcat *:E` I can see this error:
```
Unable to load resource 0x01020006 from pkg=io.ionic.notif
07-26 13:20:54.470  3379  3379 E Icon    : android.content.res.Resources$NotFoundException: Drawable android:id/icon with resource ID #0x1020006
07-26 13:20:54.470  3379  3379 E Icon    : Caused by: android.content.res.Resources$NotFoundException: Resource "android:id/icon" (1020006) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=1 r=0x1020006}
07-26 13:20:54.470  3379  3379 E Icon    :      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:810)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:680)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.content.res.Resources.getDrawableForDensity(Resources.java:892)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.content.res.Resources.getDrawable(Resources.java:834)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:324)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.graphics.drawable.Icon.loadDrawable(Icon.java:277)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:388)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:365)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:349)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.StatusBarIconView.updateDrawable(StatusBarIconView.java:327)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:289)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.NotificationData$Entry.createIcons(NotificationData.java:243)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.phone.StatusBar.createNotificationViews(StatusBar.java:11987)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.phone.StatusBar.addNotification(StatusBar.java:3658)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.systemui.statusbar.phone.StatusBar$33$2.run(StatusBar.java:10424)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.os.Handler.handleCallback(Handler.java:790)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.os.Looper.loop(Looper.java:164)
07-26 13:20:54.470  3379  3379 E Icon    :      at android.app.ActivityThread.main(ActivityThread.java:7000)
07-26 13:20:54.470  3379  3379 E Icon    :      at java.lang.reflect.Method.invoke(Native Method)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
07-26 13:20:54.470  3379  3379 E Icon    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
07-26 13:20:54.480 10775 10775 E AndroidRuntime: FATAL EXCEPTION: main
07-26 13:20:54.480 10775 10775 E AndroidRuntime: Process: io.ionic.notif, PID: 10775
07-26 13:20:54.480 10775 10775 E AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package io.ionic.notif: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=io.ionic.notif id=0x01020006) visible user=0 )
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7000)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
07-26 13:20:54.480 10775 10775 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
07-26 13:20:54.539 10964 10964 E Zygote  : isWhitelistProcess - Process is Whitelisted
07-26 13:20:54.884  2340  2340 E adbd    : recv: OPEN 000005c3 00000000 00f9:73 68 65 6C 6C 3A 67 65 74 70 72 6F 70 20 72 6F 2E 70 72 6F 64 75 63 74 2E 6D 6F 64 65 6C 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 77 69 6E 64 6F 77 20 70 6F 6C 69 63 79 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 70 73 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 63 61 74 20 2F 70 72 6F 63 2F 6E 65 74 2F 75 6E 69 78 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 75 73 65 72 0A 00 
```

**Comment by matiaslavanchi** [comment]
I had the same problems.
It seems  the plugins has some trouble with the DEFAULT ICON and the app crashes because of that
You have to set de value of smallIcon to an icon that exists.
this is your example with added icon.
`
this.localNotifications.schedule({
      text: 'Delayed ILocalNotification',
      trigger: {at: new Date(new Date().getTime() + 3600)},
      led: 'FF0000',
      smallIcon : "res://mipmap-ldpi/ic_launcher.png",
      sound: null
    }
`

**Comment by rbarriuso** [comment]
Perhaps this is fixed by https://github.com/katzer/cordova-plugin-local-notifications/commit/b8f358ebb9ed76a1ddd61892a66dee1777042bfc

**Comment by DanielRiera** [comment]
> I had the same problems.
> It seems the plugins has some trouble with the DEFAULT ICON and the app crashes because of that
> You have to set de value of smallIcon to an icon that exists.
> this is your example with added icon.
> `this.localNotifications.schedule({ text: 'Delayed ILocalNotification', trigger: {at: new Date(new Date().getTime() + 3600)}, led: 'FF0000', smallIcon : "res://mipmap-ldpi/ic_launcher.png", sound: null }`

Yes.
