### ISSUE TITLE
App is crashing in Android 

### ISSUE THREAD

**Issue by dhsinghmanh** [katzer/cordova-plugin-local-notifications#1868]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: 10
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 8.1.0
* Plugin config :       "cordova-plugin-local-notification": {},

* Ionic Version : 3.20.0

App notification should work
_Tell us what should happen_

## Actual Behavior

App is crashing
## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat
2020-01-21 16:47:11.234 2074-2117/system_process V/ActivityManager: Attempted to start a foreground service with a broken notification (no icon: Notification(channel=com.manh.tms.mobileTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE))
2020-01-21 16:47:11.235 2074-2117/system_process W/ActivityManager: Error showing notification for service
    java.lang.RuntimeException: invalid service notification: Notification(channel=com.manh.tms.mobileTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
        at com.android.server.am.ServiceRecord$1.run(ServiceRecord.java:887)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-01-21 16:47:11.240 7090-7111/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-01-21 16:47:11.242 7090-7111/? W/manh.tms.mobil: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
2020-01-21 16:47:11.242 7090-7111/? W/manh.tms.mobil: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
2020-01-21 16:47:11.242 7090-7111/? W/manh.tms.mobil: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
2020-01-21 16:47:11.243 7090-7090/? D/AndroidRuntime: Shutting down VM
2020-01-21 16:47:11.243 7090-7090/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.manh.tms.mobile, PID: 7090
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(channel=com.manh.tms.mobileTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-01-21 16:47:11.246 2074-7118/system_process I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2020-01-21

**Comment by llunn** [comment]
You might want to verify that you are passing a valid id attribute (e.g you are not passing undefined as the value of id).

**Comment by dhsinghmanh** [comment]
Id is valid. 
Are you using NotificationCompat.Builder(applicationContext.... in your plugin. 
I have founf that this thing is changed little bit. 
Now, We have to use something like this. 

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      NotificationChannel notificationChannel = new NotificationChannel(
        CUSTOM_CHANNEL_ID, CUSTOM_CHANNEL_NAME, NotificationManager.IMPORTANCE_LOW
      );
      notificationManager.createNotificationChannel(notificationChannel);
    }

    customNotificationBuilder = new NotificationCompat.Builder(applicationContext, CUSTOM_CHANNEL_ID)


Does the latest version of plugin has these changes?
