### ISSUE TITLE
not able to install the plugin

### ISSUE THREAD

**Issue by enraiser** [katzer/cordova-plugin-local-notifications#257]
Installing plugin de.appplant.cordova.plugin.local-notification...
TypeError: Cannot read property 'install' of undefined
    at /usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:275:66
    at Array.forEach (native)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:274:30)
    at /usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:158:13
    at /usr/local/lib/node_modules/cordova/node_modules/plugman/node_modules/ncallbacks/ncallbacks.js:14:21
    at /usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:308:27
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/plugman/src/util/action-stack.js:83:23)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:286:13)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:238:9)
    at /usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:218:17

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
