### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate receiver de.appplant.cordova.plugin.localnotification.Restore

### ISSUE THREAD

**Issue by nekulin** [katzer/cordova-plugin-local-notifications#304]
Error compile

java.lang.RuntimeException: Unable to instantiate receiver de.appplant.cordova.plugin.localnotification.Restore

**Comment by chuckmitchell** [comment]
I'm seeing this issue as well, it's happening after startup.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by whoshotjr** [comment]
Hi there, I currently also have this issue on Android startup, and I've got 0.8.2. Here's the log:

ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.localnotification.Restore" on path: DexPathList[[zip file "/data/app/com.***.***/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2804)
            at android.app.ActivityThread.access$1700(ActivityThread.java:178)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
            at android.os.Handler.dispatchMessage(Handler.java:111)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5637)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.localnotification.Restore" on path: DexPathList[[zip file "/data/app/com.***.***/base.apk"]

I wondered if anyone else is getting this, and if I'm doing something wrong? :)

Thanks in advance.

**Comment by whoshotjr** [comment]
For anyone else how might have the same problem - I discovered that my manifest still had legacy elements from an earlier version of the plugin. I have removed the following:

        <receiver android:name="de.appplant.cordova.plugin.localnotification.Restore">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <activity android:launchMode="singleInstance" android:name="de.appplant.cordova.plugin.localnotification.ReceiverActivity" />

and it looks like it now works.
These erroneous entries thankfully remain absent even after cordova build.
