### ISSUE TITLE
Android v2.3.7 crashed App after start

### ISSUE THREAD

**Issue by cyberkatze** [katzer/cordova-plugin-local-notifications#347]
Hallo,
on my **Android v2.3.7 API-lvl-9** crashed App after start, but on **4.4 Kitkat** same code work fine...
in documentation stay up to **API-lvl-7**. but...

what do i wrong?
ty!

```log
12-22 21:22:21.845: I/Web Console(3193): [DEBUG][doc from server length: 1] at :1752525217
12-22 21:22:21.995: W/PluginManager(3193): THREAD WARNING: exec() call to LocalNotification.add blocked the main thread for 70ms. Plugin should use CordovaInterface.getThreadPool().
12-22 21:22:22.015: D/kolin(3193): requestion  getProxyHost.return mProxyHost :null
12-22 21:22:22.035: D/CordovaLog(3193): : Line 4617553 : [DEBUG][page_Startup.js -> render() -> startup CHECKSESSION]
12-22 21:22:22.035: I/Web Console(3193): [DEBUG][page_Startup.js -> render() -> startup CHECKSESSION] at :4617553
12-22 21:22:22.155: E/dalvikvm(3193): Could not find class 'android.app.Notification$Builder', referenced from method de.appplant.cordova.plugin.localnotification.Receiver.buildNotification
12-22 21:22:22.155: W/dalvikvm(3193): VFY: unable to resolve new-instance 14 (Landroid/app/Notification$Builder;) in Lde/appplant/cordova/plugin/localnotification/Receiver;
12-22 21:22:22.155: D/dalvikvm(3193): VFY: replacing opcode 0x22 at 0x0016
12-22 21:22:22.155: D/dalvikvm(3193): VFY: dead code 0x0018-0094 in Lde/appplant/cordova/plugin/localnotification/Receiver;.buildNotification ()Landroid/app/Notification$Builder;
12-22 21:22:22.155: I/dalvikvm(3193): Could not find method android.app.Notification$Builder.setContentIntent, referenced from method de.appplant.cordova.plugin.localnotification.Receiver.setClickEvent
12-22 21:22:22.155: W/dalvikvm(3193): VFY: unable to resolve virtual method 65: Landroid/app/Notification$Builder;.setContentIntent (Landroid/app/PendingIntent;)Landroid/app/Notification$Builder;
12-22 21:22:22.155: D/dalvikvm(3193): VFY: replacing opcode 0x6e at 0x0030
12-22 21:22:22.155: D/dalvikvm(3193): VFY: dead code 0x0033-0034 in Lde/appplant/cordova/plugin/localnotification/Receiver;.setClickEvent (Landroid/app/Notification$Builder;)Landroid/app/Notification$Builder;
12-22 21:22:22.155: I/dalvikvm(3193): Could not find method android.app.Notification$Builder.getNotification, referenced from method de.appplant.cordova.plugin.localnotification.Receiver.showNotification
12-22 21:22:22.155: W/dalvikvm(3193): VFY: unable to resolve virtual method 63: Landroid/app/Notification$Builder;.getNotification ()Landroid/app/Notification;
12-22 21:22:22.155: D/dalvikvm(3193): VFY: replacing opcode 0x6e at 0x001b
12-22 21:22:22.155: I/dalvikvm(3193): Could not find method android.app.Notification$Builder.build, referenced from method de.appplant.cordova.plugin.localnotification.Receiver.showNotification
12-22 21:22:22.155: W/dalvikvm(3193): VFY: unable to resolve virtual method 62: Landroid/app/Notification$Builder;.build ()Landroid/app/Notification;
12-22 21:22:22.155: D/dalvikvm(3193): VFY: replacing opcode 0x6e at 0x0029
12-22 21:22:22.155: D/dalvikvm(3193): VFY: dead code 0x001e-0021 in Lde/appplant/cordova/plugin/localnotification/Receiver;.showNotification (Landroid/app/Notification$Builder;)V
12-22 21:22:22.155: D/dalvikvm(3193): VFY: dead code 0x002c-0030 in Lde/appplant/cordova/plugin/localnotification/Receiver;.showNotification (Landroid/app/Notification$Builder;)V
12-22 21:22:22.335: D/AndroidRuntime(3193): Shutting down VM
12-22 21:22:22.335: W/dalvikvm(3193): threadid=1: thread exiting with uncaught exception (group=0x2aac8560)
12-22 21:22:22.345: E/AndroidRuntime(3193): Uncaught handler: thread main exiting due to uncaught exception
12-22 21:22:22.375: D/skia(3193): purging 193K from font cache [20 entries]
12-22 21:22:24.455: W/System.err(3193): java.io.FileNotFoundException: /data/logcat_0.txt (Permission denied)
12-22 21:22:24.515: E/AndroidRuntime(3193): FATAL EXCEPTION: main
12-22 21:22:24.515: E/AndroidRuntime(3193): java.lang.NoClassDefFoundError: android.app.Notification$Builder
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at de.appplant.cordova.plugin.localnotification.Receiver.buildNotification(Receiver.java:124)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at de.appplant.cordova.plugin.localnotification.Receiver.onReceive(Receiver.java:86)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:1794)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.app.ActivityThread.access$2400(ActivityThread.java:117)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.os.Looper.loop(Looper.java:130)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at java.lang.reflect.Method.invoke(Method.java:507)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
12-22 21:22:24.515: E/AndroidRuntime(3193): 	at dalvik.system.NativeStart.main(Native Method)
12-22 21:22:24.555: W/System.err(3193): java.io.FileNotFoundException: /data/plog.log (Permission denied)
12-22 21:22:28.155: I/Process(3193): Sending signal. PID: 3193 SIG: 9
```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
