### ISSUE TITLE
NullPointerException with Ionic and Android 4.4.4

### ISSUE THREAD

**Issue by namoscato** [katzer/cordova-plugin-local-notifications#377]
I seem to be having some trouble configuring this plugin with my Ionic project. In my AngularJS run block, I have:

```
$ionicPlatform.ready(function() {
    window.plugin.notification.local.hasPermission(function(granted) {
        if (granted === true) {
            testNotification();
            return;
        }

        window.plugin.notification.local.registerPermission(function(granted) {
            testNotification();
        });
    });
});

function testNotification() {
    window.plugin.notification.local.add({ message: 'Great app!' });
}
```

However, when I run the application on a Nexus 7 running Android 4.4.4, I get:

```
java.lang.NullPointerException
 at de.appplant.cordova.plugin.localnotification.LocalNotification.add(LocalNotification.java:236)
 at de.appplant.cordova.plugin.localnotification.LocalNotification.access$000(LocalNotification.java:53)
 at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:84)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:841)
```

Thoughts on what I am doing wrong? Thanks in advance.

**Comment by ds8k** [comment]
I'm having the exact same problem on Android 4.4.4 and a OnePlus One. My project is Sencha Touch 2.3.1.

Everything works fine on iOS.

**Comment by ds8k** [comment]
Looks like the most recent push to master fixed the crashing issue but it doesn't look like local notifications are being scheduled now. The add event triggers but getScheduled shows no ids.

**Comment by tmaximini** [comment]
did you try passing an id to it?

```JS
var now = new Date().getTime(),
    in120sec = new Date(now + 120*1000);
window.plugin.notification.local.add({
    id:         '123',  // A unique id of the notification
    date:       in120sec,    // This expects a date object
    message:    'test',  // The message that is displayed
    title:     'TEST'  // The title of the message
});
```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
