### ISSUE TITLE
Android NullPointerException

### ISSUE THREAD

**Issue by joshbuckley182** [katzer/cordova-plugin-local-notifications#446]
I'm getting the following when trying to create a notification in Android:

```
E/PluginManager( 2965): Uncaught exception from plugin
E/PluginManager( 2965): java.lang.NullPointerException
E/PluginManager( 2965): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.execute(LocalNotification.java:133)
E/PluginManager( 2965): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:74)
E/PluginManager( 2965): 	at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
E/PluginManager( 2965): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
E/PluginManager( 2965): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:59)
E/PluginManager( 2965): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/PluginManager( 2965): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
E/PluginManager( 2965): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/PluginManager( 2965): 	at android.os.Looper.loop(Looper.java:136)
E/PluginManager( 2965): 	at android.os.HandlerThread.run(HandlerThread.java:61)
D/dalvikvm( 1261): GC_CONCURRENT freed 697K, 48% free 6335K/11960K, paused 0ms+1ms, total 8ms
```

I'm using v0.8.1 with Cordova 3.5, so I'm wondering if it might be related to #440?

**Comment by hagaisela** [comment]
got the same issue.

**Comment by joshbuckley182** [comment]
I've upgraded to Cordova 3.6 (didn't want to as I had to update Crosswalk, which is a bit of a pain), and it's working as expected now. Crosswalk on the other hand...!

**Comment by hagaisela** [comment]
cordova update alone didn't solve it for me, I had to also update the android platform (cordova platform update android)

**Comment by appastair** [comment]
Likewise. Updating Cordova worked. :smile:
