### ISSUE TITLE
Scheduling notifications with improper ids causes android app crash on retrieval. NumberFormatException

### ISSUE THREAD

**Issue by meltuhamy** [katzer/cordova-plugin-local-notifications#466]
Steps to reproduce:

```js
// 1. Schedule a notification sometime in the future, with a really big number as an id.
cordova.plugins.notification.local.schedule({
  at: new Date(new Date().getTime() + 60*1000), // 1 minute in future
  id: 1426585791468, // really long number
});

// 2. Get all scheduled notification ids
cordova.plugins.notification.local.getScheduledIds(function(ids){
  console.log(ids);
});
```

**Expect**: Get a list of scheduled notifications ids, i.e. ```[1426585791468]```

**Actual**: App crashes. Logcat:
```
E/AndroidRuntime( 5204): java.lang.NumberFormatException: Invalid int: "1426585791468"
E/AndroidRuntime( 5204): 	at java.lang.Integer.invalidInt(Integer.java:138)
E/AndroidRuntime( 5204): 	at java.lang.Integer.parse(Integer.java:413)
E/AndroidRuntime( 5204): 	at java.lang.Integer.parseInt(Integer.java:367)
E/AndroidRuntime( 5204): 	at java.lang.Integer.parseInt(Integer.java:334)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.notification.Manager.getIds(Manager.java:197)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.notification.Manager.getAll(Manager.java:246)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.notification.Manager.getIdsByType(Manager.java:210)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.getScheduledIds(LocalNotification.java:352)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$1000(LocalNotification.java:48)
E/AndroidRuntime( 5204): 	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:172)
E/AndroidRuntime( 5204): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5204): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5204): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1219):   Force finishing activity 
```

**Comment by meltuhamy** [comment]
Not sure how android uses the ids, but does it make sense to use Java ```long```s instead of ```int```s? 

If not, should a JS error be thrown if the given id doesn't fit in a 32-bit int?

**Comment by devup-sam** [comment]
I submitted a basic fix for the crashing Pull Request #459

It's not a complete fix, but at least it stops it crashing when the values are "wrong" for whatever reason

**Comment by kristianbenoit** [comment]
As far as I understand it, [`android.app.NotificationManager`](http://developer.android.com/reference/android/app/NotificationManager.html) uses int for ids, so we can't replace that with long. The good news is it can use a combination of String and int. So if we store the id in the String field instead of the int, it should work.

**Comment by katzer** [comment]
See #764
