### ISSUE TITLE
Android Lollipop - Uncaught Exception

### ISSUE THREAD

**Issue by ds8k** [katzer/cordova-plugin-local-notifications#525]
Decided to try and update to the latest version and noticed that Android doesn't do anything. Hitting this error when doing anything with the plugin:

```
E/PluginManager(10891): Uncaught exception from plugin
E/PluginManager(10891): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.concurrent.ExecutorService org.apache.cordova.CordovaInterface.getThreadPool()' on a null object reference
E/PluginManager(10891): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.execute(LocalNotification.java:133)
E/PluginManager(10891): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:74)
E/PluginManager(10891): 	at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
E/PluginManager(10891): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
E/PluginManager(10891): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:59)
E/PluginManager(10891): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/PluginManager(10891): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
E/PluginManager(10891): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/PluginManager(10891): 	at android.os.Looper.loop(Looper.java:135)
E/PluginManager(10891): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by boltex** [comment]
HAve the same problem!

**Comment by boltex** [comment]
Edited my previous comment with a solution!

**Comment by katzer** [comment]
local-notification will support android 4 starting with v0.9
