### ISSUE TITLE
Cannot find module 'cordova-lib/src/cordova/platforms'

### ISSUE THREAD

**Issue by vection** [katzer/cordova-plugin-local-notifications#531]
I am working with:

```
OS: Mac OS X Yosemite
Node version: v0.12.2
Cordova version: 5.0.0
```

I get the following error when adding the plugin:

```
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Cannot find module 'cordova-lib/src/cordova/platforms'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:48:12)
    at module.exports (/Users/ben/Documents/coding/meet2run/meet2run/plugins/de.appplant.cordova.plugin.local-notification/scripts/ios/didRegisterUserNotificationSettings.js:42:29)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
```

I think this worked before cordova 5.0.0. Is anybody else getting the same error?

**Comment by butchewing** [comment]
I have the same issue. I am also having the [same issue with the Badge plugin](https://github.com/katzer/cordova-plugin-badge/issues/29). I think this is a result of Cordova v5.0.0.

**Comment by AttackTheDarkness** [comment]
Ran into the same problem. It looks to me like the platforms stuff moved from cordova/platforms to platforms/platforms. I'll submit a pull request for this.
