### ISSUE TITLE
Plugin fails to install, can't find cordova-plugin-device

### ISSUE THREAD

**Issue by joshhunt** [katzer/cordova-plugin-local-notifications#602]
Installing your plugin now fails with:

```shell
Fetching plugin "cordova-plugin-device" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-device
npm http 404 http://registry.cordova.io/cordova-plugin-device
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: 404 Not Found: cordoba-plugin-device
```

I can verify this with `cordova plugin add cordoba-plugin-device`

```shell
Fetching plugin "cordova-plugin-device" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-device
npm http 404 http://registry.cordova.io/cordova-plugin-device
Error: 404 Not Found: cordova-plugin-device
```

Whereas ` cordova plugin add org.apache.cordova.device` works

```shell
Fetching plugin "org.apache.cordova.device" via plugin registry
npm http GET http://registry.cordova.io/org.apache.cordova.device
npm http 304 http://registry.cordova.io/org.apache.cordova.device
Installing "org.apache.cordova.device" for android
Installing "org.apache.cordova.device" for ios
```

It appears you changed the dependency ID, which is causing this error. Installing from the previous git hash https://github.com/katzer/cordova-plugin-local-notifications/commit/bde4fd25454e85e64b9a04083e020b591d79440b works properly

**Comment by PKnittel** [comment]
Update your Cordova CLI to version 5.1.1 and try again. Apache changed the namespaces for all core-plugins. Hope that helps you.

**Comment by joshhunt** [comment]
Installing latest from git still fails. As I documented in my original issue, it appears `cordova-plugin-device` is not a valid Cordova plugin

```shell
~/D/s/app ( master) → cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications.git" via git clone
Installing "de.appplant.cordova.plugin.local-notification" for android
Fetching plugin "cordova-plugin-device" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-device
npm http 404 http://registry.cordova.io/cordova-plugin-device
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: 404 Not Found: cordova-plugin-device
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
Error: 404 Not Found: cordova-plugin-device
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by PKnittel** [comment]
try 'cordova platform rm android' and 'cordova platform add android' again.

As you can see here:
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html
the namespaces for core-plugins have changed with cordova5.
