### ISSUE TITLE
top level Exception while compiling android

### ISSUE THREAD

**Issue by dimiandre** [katzer/cordova-plugin-local-notifications#616]
for me android build fails with this

:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/
NotificationCompat$Action;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:45
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Program Files (x86)\Android\android-sdk\build-tools\22.0.1\dx.bat --d
ex --no-optimize --output C:\Users\Andrea\Desktop\Mirasol\miraApp\platforms\andr
oid\build\intermediates\dex\debug --input-list=C:\Users\Andrea\Desktop\Mirasol\m
iraApp\platforms\android\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support
/v4/app/NotificationCompat$Action;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)

BUILD FAILED
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

Total time: 6.681 secs

C:\Users\Andrea\Desktop\Mirasol\miraApp\platforms\android\cordova\node_modules\q
\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\Andrea\Desktop\Mirasol\
miraApp\platforms\android\gradlew cdvBuildDebug -b C:\Users\Andrea\Desktop\Miras
ol\miraApp\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Andrea\AppData\Roaming\npm\node_modules\c
ordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

C:\Users\Andrea\Desktop\Mirasol\miraApp>

**Comment by fvaliente-globalway** [comment]
getting the same error - did you find a solution yet?

**Comment by Sadzeih** [comment]
Same error, removing an re adding plugins didn't work

**Comment by marnick-hartgers** [comment]
Same story. And it's causing big problems

**Comment by fvaliente-globalway** [comment]
hmm, double checked what I did and it seemed that I also removed ../plugins/de.appplant.cordova.plugin.local-notification/libs/android/android-support-v4.jar as it was already available at ../platforms/android/libs/ of my ionic project.

**Comment by roysG** [comment]
same problem for me, any news?

**Comment by katzer** [comment]
Has been fixed from my side but there might still be incompatibilities with other plugins.
