### ISSUE TITLE
Uncaught java.lang.NullPointerException in LocalNotification.execute()

### ISSUE THREAD

**Issue by blanedaze** [katzer/cordova-plugin-local-notifications#642]
I have encountered the following error while using a forked version of this plugin:

    E/PluginManager﹕ Uncaught exception from plugin
    java.lang.NullPointerException
            at de.appplant.cordova.plugin.localnotification.LocalNotification.execute(LocalNotification.java:136)
            at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:61)
            at org.apache.cordova.PluginManager.execHelper(PluginManager.java:235)
            at org.apache.cordova.PluginManager.exec(PluginManager.java:220)
            at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:59)
            at com.appgyver.webview.AGCordovaBridge.exec(AGCordovaBridge.java:26)
            at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
            at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)

I actually use my own forked version of this plugin [in here](https://github.com/blanedaze/cordova-plugin-local-notifications), which I had only removed `android-support-v4.jar` from the repository and `<lib-file src="libs/android/android-support-v4.jar" />` from `plugin.xml`. This changes allow me to include this plugin successfully into Appgyver's Supersonic application.

Is it possible for this problem to be fixed?

**Comment by mix3d** [comment]
Since the plugin still depends on the android support library, how are you adding it back in on compile time?

**Comment by blanedaze** [comment]
Since I'm using appgyver's build environment, I assume that the android support library is actually included by default in the builder and added automatically during compilation.

**Comment by katzer** [comment]
@blanedaze 
@mix3d 

this has been fixed.
