### ISSUE TITLE
Android 6.0, Emulator and crash while resuming app from notification

### ISSUE THREAD

**Issue by Gob0** [katzer/cordova-plugin-local-notifications#682]
Hi, 

i'm trying to use plugin in a cordova app and my app still crash after i clicked on notification. This is driving me crazy :-/

So, i add notification like this:
cordova.plugins.notification.local.schedule( { id: inId, title: stTitle, text: stMsg+' ('+inId+')', at: new Date() + 1000 } );

I register clicke event like this:
cordova.plugins.notification.local.on("click", function (notification, state) { 
	setTimeout(function() {
		console.log('click on notification') 
	}, 1);
});

I run the app in emulator (Android 6, "mesa GPU", Linux Debian) and the plugin does its magic! the notification appears! And if i click on it it, crash happens :-( 

Can anyone help me? Thanks in advance! 

-- 
Gauthier

--------- beginning of crash
FATAL EXCEPTION: main
Process: com.opzo.game.zoopmem, PID: 2524
java.lang.RuntimeException: Unable to resume activity {com.opzo.game.zoopmem/de.appplant.cordova.plugin.localnotification.ClickActivity}: java.lang.IllegalStateException: Activity {com.opzo.game.zoopmem/de.appplant.cordova.plugin.localnotification.ClickActivity} did not call finish() prior to onResume() completing
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
   at android.app.ActivityThread.-wrap11(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Activity {com.opzo.game.zoopmem/de.appplant.cordova.plugin.localnotification.ClickActivity} did not call finish() prior to onResume() completing
   at android.app.Activity.performResume(Activity.java:6324)
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
... 10 more

**Comment by randdusing** [comment]
I'm getting this same error on Android 6.0 devices, but I don't have any click handlers are registered.

**Comment by randdusing** [comment]
Based on http://stackoverflow.com/questions/32169303/activity-did-not-call-finish-api-23, I added the following code to ClickActivity.java:

```java
   @Override
    protected void onStart() {
      super.onStart();
      setVisible(true);
    }
```

**Comment by Gob0** [comment]
Thanks Randdusing! (i have to admit that since Sep. 23, i wasn't expecting answer anymore) 

I'll give a shot quickly. Thanks again!
