### ISSUE TITLE
Getting a non-existing notification leads to crash on android

### ISSUE THREAD

**Issue by pas** [katzer/cordova-plugin-local-notifications#696]
Tested with: Genymotion, Android 4.3

```javascript
     document.addEventListener('deviceready', function() {
		window.plugin.notification.local.get('1002', function(notification) { console.log(notification) });
	 }, false);
```

StackTrace:
```
E/AndroidRuntime( 1961): FATAL EXCEPTION: pool-1-thread-5
E/AndroidRuntime( 1961): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime( 1961): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime( 1961): 	at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime( 1961): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.getOptions(LocalNotification.java:474)
E/AndroidRuntime( 1961): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.getSingle(LocalNotification.java:396)
E/AndroidRuntime( 1961): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$1200(LocalNotification.java:51)
E/AndroidRuntime( 1961): 	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:181)
E/AndroidRuntime( 1961): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/AndroidRuntime( 1961): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/AndroidRuntime( 1961): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by katzer** [comment]
Duplicate #705
