### ISSUE TITLE
Faild to install plugin

### ISSUE THREAD

**Issue by mirkofisic** [katzer/cordova-plugin-local-notifications#698]
I remove plugin from project and now I want to add plugin again and I got error:

Failed to install 'de.appplant.cordova.plugin.local-notification':Error: cmd: Command failed with exit code ENOENT
    at ChildProcess.whenDone (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\s
rc\cordova\superspawn.js:139:23)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
Error: cmd: Command failed with exit code ENOENT
    at ChildProcess.whenDone (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\s
rc\cordova\superspawn.js:139:23)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by mirkofisic** [comment]
Solved with installation WinANT

**Comment by katzer** [comment]
:+1:
