### ISSUE TITLE
Android Index out of bounds crash on notification query

### ISSUE THREAD

**Issue by frekky** [katzer/cordova-plugin-local-notifications#705]
This occurs after scheduling a notification using the API, waiting until the notification is triggered and then querying the notification. This is demonstrated here:
```javascript
cordova.plugins.notification.local.schedule({
				    id: Math.floor(Math.abs(Math.random() * 10000000000)),
				    title: "Some text",
				    text: "more text",
				    every: "day",
				    at: 0, // to schedule immediately
				    ongoing: false
				});

// wait until notification has triggered "immediately"
setTimeout(function() {
cordova.plugins.notification.local.get(sameIdAsBefore, function (n) {
						// update the notification to some different text
						// never gets to here; crash occurs before
						cordova.plugins.notification.local.update({
						    id: n.id,
						    text: "different text",
						    at: 0 // to update + reschedule immediately
						});
				});
}, 10000); // "now" is quite a long time for notifications, apparently
```

which then crashes with the error (from logcat):
```logcat
E/AndroidRuntime(12559): FATAL EXCEPTION: pool-1-thread-3
E/AndroidRuntime(12559): Process: com.example.crashyApp, PID: 12559
E/AndroidRuntime(12559): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime(12559): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime(12559): 	at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime(12559): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.getOptions(LocalNotification.java:474)
E/AndroidRuntime(12559): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.getSingle(LocalNotification.java:396)
E/AndroidRuntime(12559): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$1200(LocalNotification.java:51)
E/AndroidRuntime(12559): 	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:181)
E/AndroidRuntime(12559): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12559): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12559): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  831):   Force finishing activity android/com.android.internal.app.ChooserActivity
W/ActivityManager(  831):   Force finishing activity com.example.crashyApp/.MainActivity
I/ActivityManager(  831): Killing 11578:com.android.keychain/1000 (adj 15): empty #17
```

If I figure out how to work around this, I'll post details here.
Thanks

**Comment by katzer** [comment]
Fixed with 2d4033c32d425bee139f6badbd273c88c53585e6
