### ISSUE TITLE
example app build fail

### ISSUE THREAD

**Issue by dejan7** [katzer/cordova-plugin-local-notifications#752]
i get this error:

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\Dejan\AppData\Local\Android\sdk\build-tools\22.0.1\dx.bat --dex --no-optimize --output C:\wamp\www\notifeg\platforms\android\build\intermediates\dex\debug --input-list=C:\wamp\www\notifeg\platforms\android\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jrbistuer** [comment]
Same here! Has anyone found the issue?

**Comment by katzer** [comment]
The import into Android Studio is still not the easiest one. It happens if you import to much ;) Only include the source code for the platform, not the plugin or build or gen folder.

Also you the `--link` flag when adding plugins in general.

**Comment by mr-sparks** [comment]
@katzer 

I have exactly the same problem :) What does one have to do once this happens? I tried everything from removing android platform, re-adding, updating plugins, etc. ?
