### ISSUE TITLE
Don't compile for android on phonegap build online

### ISSUE THREAD

**Issue by noveweb** [katzer/cordova-plugin-local-notifications#801]
Don't compile for android in phonegap. Error:

Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:183:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by noveweb** [comment]
Now working on IOS using npm and dependence plugin settings:

<gap:plugin name="org.apache.cordova.device" spec="0.2.12" source="pgb" />
<gap:plugin name="de.appplant.cordova.common.registerusernotificationsettings" spec="1.0.1" source="pgb" />
<gap:plugin name="de.appplant.cordova.plugin.local-notification" spec="0.8.2" source="npm" />

Phonegap Android build error:

Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:183:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by noveweb** [comment]
Solution:
Add this line to config.xml > <preference name="android-build-tool" value="gradle" /> 

The config.xml working fine on android and ios:

<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="org.apache.cordova.device" spec="0.2.12" source="pgb" />
<gap:plugin name="de.appplant.cordova.common.registerusernotificationsettings" spec="1.0.1" source="pgb" />
<gap:plugin name="de.appplant.cordova.plugin.local-notification" spec="0.8.2" source="npm" />
