### ISSUE TITLE
IOS BUILD FAILED

### ISSUE THREAD

**Issue by modestoartur** [katzer/cordova-plugin-local-notifications#815]
cordova platform add ios
Adding ios project...
Running command: /Users/MDO/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/create /Users/MDO/Desktop/reminder/platforms/ios com.reminder.app ReminderApp --cli
iOS project created with cordova-ios@3.9.2
Installing "cordova-plugin-whitelist" for ios
Installing "de.appplant.cordova.plugin.local-notification" for ios
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "/Users/MDO/Desktop/reminder/plugins/org.apache.cordova.device" being installed.
Installing "org.apache.cordova.device" for ios

```
    Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
    https://github.com/katzer/cordova-plugin-local-notifications#supporting

    Thank you!
```

The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Failed to install 'de.appplant.cordova.plugin.local-notification':TypeError: platforms[platform].parser is not a function
    at getAbsPath (/Users/MDO/Desktop/reminder/plugins/de.appplant.cordova.plugin.local-notification/scripts/ios/didRegisterUserNotificationSettings.js:65:22)
    at module.exports (/Users/MDO/Desktop/reminder/plugins/de.appplant.cordova.plugin.local-notification/scripts/ios/didRegisterUserNotificationSettings.js:93:18)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:151:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:129:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
Error: platforms[platform].parser is not a function

**Comment by kjt1212** [comment]
I am facing the same issue. Did anyone manage to find the solution yet?

**Comment by rwillett** [comment]
Is this still an issue or can it be closed?

**Comment by rwillett** [comment]
No update so closing
