### ISSUE TITLE
cant install / npm issues

### ISSUE THREAD

**Issue by joshribakoff** [katzer/cordova-plugin-local-notifications#836]
This plugin wont install

```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.1

module.js:340
    throw err;
          ^
Error: Cannot find module 'umask'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/npm/lib/utils/umask.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I ran npm install -g umask, and now I get a new error:

```
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.1

/usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19
  , fs = gfs.gracefulify(require('fs'))
             ^
TypeError: Object #<Object> has no method 'gracefulify'
    at /usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19:14
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:469:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:27:21)
    at Module._compile (module.js:456:26)
[josh@localhost lift2]$ sudo npm install -g gracefulify
npm ERR! Linux 4.2.3-300.fc23.x86_64
npm ERR! argv "node" "/bin/npm" "install" "-g" "gracefulify"
npm ERR! node v0.10.36
npm ERR! npm  v3.5.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/gracefulify
npm ERR! 404 
npm ERR! 404  'gracefulify' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/josh/www/lift2/npm-debug.log
[josh@localhost lift2]$ 

```

**Comment by robochris** [comment]
Im not sure if this will help but you could do 
`npm i de.appplant.cordova.plugin.local-notification`
I got this information [here](https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification)

**Comment by rwillett** [comment]
Is this an issue or can it be closed ? Its now over a year old.
