### ISSUE TITLE
Failed to install 'de.appplant.cordova.plugin.local-notification':TypeError: undefined is not a function at getAbsPath

### ISSUE THREAD

**Issue by jlamim** [katzer/cordova-plugin-local-notifications#879]
I am using fork https://github.com/NorthMcCormick/cordova-plugin-local-notifications to receive notifications on iOS 9, but the error described in the title and in full below happens when I run command "cordova plugin add https://github.com/NorthMcCormick/cordova-plugin-local-notifications":

```
MacBook-Pro-de-Jonathan:app-buzina jlamim$ cordova plugin add https://github.com/NorthMcCormick/cordova-plugin-local-notifications
Fetching plugin "https://github.com/NorthMcCormick/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/NorthMcCormick/cordova-plugin-local-notifications" checked out to git ref "master".
Installing "de.appplant.cordova.plugin.local-notification" for android
Dependent plugin "cordova-plugin-device" already installed on android.

        Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications#supporting

        Thank you!

Installing "de.appplant.cordova.plugin.local-notification" for ios
Dependent plugin "cordova-plugin-device" already installed on ios.

        Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications#supporting

        Thank you!

The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Failed to install 'de.appplant.cordova.plugin.local-notification':TypeError: undefined is not a function
    at getAbsPath (/Volumes/WebRepo/app-buzina/plugins/de.appplant.cordova.plugin.local-notification/scripts/ios/didRegisterUserNotificationSettings.js:65:22)
    at module.exports (/Volumes/WebRepo/app-buzina/plugins/de.appplant.cordova.plugin.local-notification/scripts/ios/didRegisterUserNotificationSettings.js:93:18)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:145:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
Error: undefined is not a function
MacBook-Pro-de-Jonathan:app-buzina jlamim$ 
```

Can anyone tell me what the problem and how to solve?

**Comment by macfam** [comment]
I am using an older version of Cordova (and the CLI) and received the same error. I had to install an older version of the plugin to avoid the error:

cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1

Thanks to @shallsaur for the tip: https://github.com/katzer/cordova-plugin-local-notifications/issues/841#issuecomment-172752988

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as its now over a year old?

**Comment by lajos93** [comment]
@rwillett yes its still an issue
