### ISSUE TITLE
Android crash java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by djangojack** [katzer/cordova-plugin-local-notifications#883]
Just got this crash report. It seems to be related to bitmaps and the local notification plugin:

java.lang.OutOfMemoryError
in dalvik.system.VMRuntime.newNonMovableArray

Android version: Android 5.0
Device: L-01F (g2)

java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 187206 free bytes and 182KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
	at de.appplant.cordova.plugin.notification.AssetUtil.getIconFromUri(AssetUtil.java:390)
	at de.appplant.cordova.plugin.notification.Options.getIconBitmap(Options.java:273)
	at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:132)
	at de.appplant.cordova.plugin.notification.Manager.get(Manager.java:413)
	at de.appplant.cordova.plugin.notification.Manager.getByIds(Manager.java:231)
	at de.appplant.cordova.plugin.notification.Manager.getAll(Manager.java:245)
	at de.appplant.cordova.plugin.notification.Manager.cancelAll(Manager.java:179)
	at de.appplant.cordova.plugin.localnotification.LocalNotification.cancelAll(LocalNotification.java:264)
	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$300(LocalNotification.java:50)
	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by mix3d** [comment]
How big is your icon.png file? On an LG G2, an older device, running 5.0 (assuming a custom rom), it might struggle to inflate a large icon.png file. I would recommend creating a proper 24x24dp Statusbar asset and setting it to the icon value `opts.icon = "res://name-of-asset"`, ortherwise it will try to create a bitmap of the app icon itself, which is not designed to be run as the notification icon.

**Comment by djangojack** [comment]
@mix3d the status bar icon was fine. The large icon was 512x512, which was too large. Reducing it to 144x144 solved the problem. Thanks!
