### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by blukis** [katzer/cordova-plugin-local-notifications#961]
Here's a crash stack trace i got on Android. Looks like it's related to icon image file I provided. (I think I've seen local crashes before when referencing a local smallIcon/icon that did not exist, but couldn't swear it's related.) Is this something you could wrap some ~try/catch around? (I think notification appearing w/ default icon would always be preferred to app-crashing.)

Using this in my config.xml:
`<plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.4" />`

Crash stack trace follows...

`java.lang.OutOfMemoryError
    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:634)
    at de.appplant.cordova.plugin.notification.AssetUtil.getIconFromUri(AssetUtil.java:367)
    at de.appplant.cordova.plugin.notification.Options.getIconBitmap(Options.java:293)
    at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:141)
    at de.appplant.cordova.plugin.notification.Manager.get(Manager.java:416)
    at de.appplant.cordova.plugin.notification.Manager.getByIds(Manager.java:234)
    at de.appplant.cordova.plugin.notification.Manager.getAll(Manager.java:248)
    at de.appplant.cordova.plugin.notification.Manager.clearAll(Manager.java:165)
    at de.appplant.cordova.plugin.localnotification.LocalNotification.clearAll(LocalNotification.java:296)
    at de.appplant.cordova.plugin.localnotification.LocalNotification.access$500(LocalNotification.java:50)
    at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:158)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)`

**Comment by rwillett** [comment]
Is this still an issue?
